# Generated by Django 2.2.11 on 2020-07-14 13:57

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='djangocms_blog_post_post_content', slotname='Post Content', to='cms.Placeholder'),
        ),
        migrations.AlterField(
            model_name='post',
            name='liveblog',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='djangocms_blog_post_live_blog', slotname='Live Blog', to='cms.Placeholder'),
        ),
        migrations.AlterField(
            model_name='post',
            name='media',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='djangocms_blog_post_media', slotname='Media', to='cms.Placeholder'),
        ),
    ]
