# Generated by Django 2.2.13 on 2020-09-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_blog', '0039_auto_20200331_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publish',
        ),
        migrations.AddField(
            model_name='posttranslation',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='publish'),
        ),
    ]
