# Generated by Django 2.2.13 on 2020-09-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_blog', '0041_make_images_translatable'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttranslation',
            name='is_publish',
            field=models.BooleanField(default=True, verbose_name='publish'),
        ),
    ]
