# Generated by Django 2.2.13 on 2020-09-30 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_blog', '0042_posttranslation_is_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publish',
        ),
    ]
