# Generated by Django 2.2.13 on 2020-10-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_blog', '0043_remove_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttranslation',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='publish'),
        ),
    ]
